
#test template for setting different environment
spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/depts
    password: root123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"Hello, World!"'

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/depts-qa
    password: root123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"Hello, World!"'

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/depts
    password: root123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"Hello, World!"'

